language: node_js
node_js: 12.18.1
os:
- windows
- linux
script:
- npm run dist

deploy:
  provider: releases
  api_key:
    secure: GBns0GfiwNoa67DInt4oQbBcbVS9x4c41uh5NEbGW2zL4Qh9Wfc+1ldO5wbSbrSNHnILLKCjKT4FkuFNp9nCMofPU7xXFEVPfTNaEym6HQYLrZ502pG1Er8dRVYPdXs6hHwCiOJlUO7ukELPeQef7GCjBqJMzdBtFBhfdvJ/zNwo28Ta/d/MVwEaBGfBy8ySmmVYgwY8Ax9z3tzxjcBqR/f2bEyg7Mansa/cdjx0IfUDGzylrY6UbEr5OYQZ6609E1YfDjpJbnk4NXtgqi7a6GQiWgciRoWaWtYrXl1UEaRglLd7WrXKr/nkR9YO70S8NrX0/BmIe4fuOBSo07P8hPQyUgahIL4TJhS3cMG72/w5S3zI/qMaSSobKpFRgfL/gZzSI24qg/XH+RhkMspW6fxlfOd2O6at2+vh3dq/Sdnax6uidVE1wU77vuJjaI7hvsK8LdjV+kJD+12bXGTAGoo7bH2hokvSanySZZwfqVPIg0/ol99wafJa/wxWCndiybX4ibQAKNnG+jZNulO1oCKDeDIoQVfq3lYwKakxXDBwt3ZxhbTwLoNGGrODw3G7WI7TeZRDxrp3mXUjh+ntLPYai1CtN+729WT9oPc8ByQTe2Y6PCTQWQQ1/4Gs2O0HocGz9NNh1XEK4f1U0k7KrNgHEa7WOQJjL0Hr7xeq+ZM=
  file: 
    - "*.exe"
    - "*.deb"
  on:
    repo: BlueBubblesApp/BlueBubbles-Desktop-App
    branch: maxwell/dev
  skip_cleanup: 'true'
  draft: 'true'
