language: node_js
os:
- windows
- linux
env:
  global:
    secure: DawnFFmjTETHMyAoV13X83YUupttuF8b23yWhOIMXWoh8/51MFt7OtKbUf2Em+nU0kH8YjnPnV3lLFQgrSkmu9n1x/RQGCpUueBeTPodKr5fHQSTmls53BS5M1nky6SlSWwvNyYp7OZFI/x+PlrR0eXXFkutXnTG2jp8DM2Wl2jMQJz6DC63RXAFrQaHKR5j4YKoUkyUTQTQB2tewMSdT2IsQPFu7K/NZ9weV+bCN+8quMsdAM6+Cxe8apuJWd8GLPS4pAmTnHDeyQstgLlke58RlImiMr72rS6Tcydp3hmHaylFQh6N4R4eD805V+GLAz/fbmNm8IsimVZn4kpQakJC5gwxnCBpJY1VjodZExCoHm/kt6Mar5lhwNKwJ5erFP/mm8nxRJfyFfttRGV2d8Ju+3mOEFbb4gVBj3/pUzDLTTkNGkICXd39dpgZC/Fl70XmXEjDILOAmBQBbDlANxYx7xlcAgymFdJs4lw+uzVSWaNSgfY1Y+asmE4UkCoe6VzpDv+dy2VywYu4ODi30tS9bTnxaZl+d51SWOmFGmIOx5hxrFHqE4oy2zxyfFEIb83yku+tUgJEFJogAdui7Ni23RQjJwGKDo9R4Ts9LVkSUz/qHfrIXv7i5I8wNBhoAQW6/mHopRakKMUiKskOicrNF0zxmtoSlO3upzwSQi4=


script:
  - npm run dist

# jobs: 
#   include:
#     - stage: Deploy Windows
#       # if: tag IS present
#       os: windows
#       script: 
#         - npm run dist
#     - stage: Deploy Linux
#       # if: tag IS present
#       os: linux
#       script: 
#         - npm run dist